"""Disk storage and content checks for uploaded documents.

The file type is decided from the bytes, never from the browser's name or Content-Type. Only formats a small
business actually files are accepted, and Office files with macros are refused.
"""
import hashlib
import io
import os
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path

from ..config import get_settings

# Kinds we accept: (content type, extension).
PDF = ("application/pdf", "pdf")
PNG = ("image/png", "png")
JPEG = ("image/jpeg", "jpg")
WEBP = ("image/webp", "webp")
DOCX = ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx")
XLSX = ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx")
TEXT = ("text/plain", "txt")
CSV = ("text/csv", "csv")

# Shown inline (in a sandbox) when asked; everything else is always an attachment.
INLINE_OK = {PDF[0], PNG[0], JPEG[0], WEBP[0]}
MAX_ZIP_ENTRIES = 2000
MAX_ZIP_RATIO = 100  # uncompressed / compressed; anything above looks like a zip bomb


class Rejected(ValueError):
    pass


@dataclass
class Detected:
    content_type: str
    extension: str


def _office(data: bytes) -> tuple[str, str]:
    try:
        z = zipfile.ZipFile(io.BytesIO(data))
        infos = z.infolist()
    except zipfile.BadZipFile:
        raise Rejected("The file looks like a damaged ZIP/Office file")
    if len(infos) > MAX_ZIP_ENTRIES or sum(i.file_size for i in infos) > MAX_ZIP_RATIO * max(len(data), 1):
        raise Rejected("The Office file's contents are too large to accept")
    names = {i.filename for i in infos}
    if "[Content_Types].xml" not in names:
        raise Rejected("ZIP archives are not accepted; upload the files inside them")
    if any(n.lower().endswith("vbaproject.bin") for n in names):
        raise Rejected("Office files with macros are not accepted")
    if any(n.startswith("word/") for n in names):
        return DOCX
    if any(n.startswith("xl/") for n in names):
        return XLSX
    raise Rejected("Only Word (.docx) and Excel (.xlsx) Office files are accepted")


def detect(data: bytes, filename: str) -> Detected:
    """Identify the file from its first bytes. Raises Rejected for anything not on the allow-list."""
    head = data[:16]
    if head.startswith(b"%PDF-"):
        kind = PDF
    elif head.startswith(b"\x89PNG\r\n\x1a\n"):
        kind = PNG
    elif head.startswith(b"\xff\xd8\xff"):
        kind = JPEG
    elif head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        kind = WEBP
    elif head.startswith(b"PK\x03\x04"):
        kind = _office(data)
    else:
        if b"\x00" in data:
            raise Rejected("This file type is not accepted. Use PDF, JPEG, PNG, WebP, Word, Excel, text or CSV")
        try:
            data.decode("utf-8")
        except UnicodeDecodeError:
            raise Rejected("Text files must be UTF-8")
        kind = CSV if filename.lower().endswith(".csv") else TEXT
    return Detected(*kind)


def safe_name(name: str, extension: str) -> str:
    """A display/download name: no path parts or control characters, and the detected extension."""
    base = os.path.basename(name.replace("\\", "/")).strip() or "document"
    base = "".join(ch for ch in base if ch.isprintable() and ch not in '"<>:|?*')[:150]
    stem = base.rsplit(".", 1)[0] if "." in base else base
    return f"{stem or 'document'}.{extension}"


def _root() -> Path:
    return Path(get_settings().storage_dir).resolve()


def _path(key: str) -> Path:
    p = (_root() / key).resolve()
    if _root() not in p.parents:  # keys are generated by us, but never trust a path blindly
        raise Rejected("Invalid storage key")
    return p


def save(org_id: int, data: bytes) -> tuple[str, str]:
    """Write the bytes atomically. Returns (storage_key, sha256)."""
    key = f"{org_id}/{uuid.uuid4().hex}"
    path = _path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".part")
    with open(tmp, "wb") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    return key, hashlib.sha256(data).hexdigest()


def read(key: str) -> bytes:
    return _path(key).read_bytes()


def remove(key: str) -> None:
    try:
        _path(key).unlink()
    except FileNotFoundError:
        pass
