"""phase2 trade

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 19:44:45.069602
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.String(length=7), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'doc_type', 'fiscal_year')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_organization_id'), ['organization_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(customer_id IS NULL) <> (supplier_id IS NULL)', name='ck_payments_party'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_pos'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_organization_id'), ['organization_id'], unique=False)

    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('supplier_reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=60), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credited_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number'),
    sa.UniqueConstraint('organization_id', 'supplier_id', 'supplier_invoice_number')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.CheckConstraint('quantity > 0 AND received_quantity >= 0', name='ck_pol_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('line_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_lines_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credited_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_sales_inv_org_date', ['organization_id', 'invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_organization_id'), ['organization_id'], unique=False)

    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('restock', sa.Boolean(), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_sales_invoice_id'), ['sales_invoice_id'], unique=False)

    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_lines_goods_receipt_id'), ['goods_receipt_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=True),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('(sales_invoice_id IS NULL) <> (purchase_invoice_id IS NULL)', name='ck_alloc_target'),
    sa.CheckConstraint('amount > 0', name='ck_alloc_amount_pos'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_purchase_invoice_id'), ['purchase_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_sales_invoice_id'), ['sales_invoice_id'], unique=False)

    op.create_table('purchase_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoice_lines_purchase_invoice_id'), ['purchase_invoice_id'], unique=False)

    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_returns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sales_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('line_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_lines_sales_invoice_id'), ['sales_invoice_id'], unique=False)

    op.create_table('credit_note_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_invoice_line_id'], ['sales_invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_lines_credit_note_id'), ['credit_note_id'], unique=False)

    op.create_table('purchase_return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_return_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_return_lines_purchase_return_id'), ['purchase_return_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_code', sa.String(length=2), nullable=True))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numbering_prefixes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('invoice_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('round_invoices_to_rupee', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('round_invoices_to_rupee')
        batch_op.drop_column('payment_instructions')
        batch_op.drop_column('invoice_terms')
        batch_op.drop_column('numbering_prefixes')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('state_code')

    with op.batch_alter_table('purchase_return_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_return_lines_purchase_return_id'))

    op.drop_table('purchase_return_lines')
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_lines_credit_note_id'))

    op.drop_table('credit_note_lines')
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_lines_sales_invoice_id'))

    op.drop_table('sales_invoice_lines')
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_returns_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_organization_id'))

    op.drop_table('purchase_returns')
    with op.batch_alter_table('purchase_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_lines_purchase_invoice_id'))

    op.drop_table('purchase_invoice_lines')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_sales_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_purchase_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('goods_receipt_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_lines_goods_receipt_id'))

    op.drop_table('goods_receipt_lines')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_sales_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_customer_id'))

    op.drop_table('credit_notes')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_customer_id'))
        batch_op.drop_index('ix_sales_inv_org_date')

    op.drop_table('sales_invoices')
    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_lines_quotation_id'))

    op.drop_table('quotation_lines')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_purchase_order_id'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_organization_id'))

    op.drop_table('purchase_invoices')
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipts_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_organization_id'))

    op.drop_table('goods_receipts')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_customer_id'))

    op.drop_table('quotations')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_organization_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_organization_id'))
        batch_op.drop_index('ix_suppliers_org_name')

    op.drop_table('suppliers')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
