"""phase3 finance

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 20:11:21.996691
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kind', 'name')
    )
    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_categories_organization_id'), ['organization_id'], unique=False)

    op.create_table('money_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    with op.batch_alter_table('money_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_money_accounts_organization_id'), ['organization_id'], unique=False)

    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name='ck_tax_rate_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rates_organization_id'), ['organization_id'], unique=False)

    op.create_table('finance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('payee', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'transfer') = (to_account_id IS NOT NULL)", name='ck_fin_transfer'),
    sa.CheckConstraint('amount > 0', name='ck_fin_amount_pos'),
    sa.CheckConstraint('tax_amount >= 0 AND tax_amount <= amount', name='ck_fin_tax'),
    sa.ForeignKeyConstraint(['account_id'], ['money_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['money_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.create_index('ix_fin_org_date', ['organization_id', 'entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_entries_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prices_include_tax_default', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('logo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sa.String(length=20), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payments_account_id', 'money_accounts', ['account_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_cost', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prices_include_tax', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True))

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prices_include_tax', sa.Boolean(), nullable=False, server_default=sa.false()))

    op.execute("UPDATE products SET avg_cost = purchase_price")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_column('prices_include_tax')

    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('prices_include_tax')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('avg_cost')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_payments_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo')
        batch_op.drop_column('prices_include_tax_default')

    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_entries_organization_id'))
        batch_op.drop_index('ix_fin_org_date')

    op.drop_table('finance_entries')
    with op.batch_alter_table('tax_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rates_organization_id'))

    op.drop_table('tax_rates')
    with op.batch_alter_table('money_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_money_accounts_organization_id'))

    op.drop_table('money_accounts')
    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_categories_organization_id'))

    op.drop_table('finance_categories')
    # ### end Alembic commands ###
