"""phase4 service employees

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 17:36:18.975913
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('job_role', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_technician', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'employee_code'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_organization_id'), ['organization_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('check_in', sa.String(length=5), nullable=True),
    sa.Column('check_out', sa.String(length=5), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_work_date'), ['work_date'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_dates'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_organization_id'), ['organization_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('site_location', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=True),
    sa.Column('installed_by_ticket_id', sa.Integer(), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'serial_number')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_warranty_until'), ['warranty_until'], unique=False)

    op.create_table('maintenance_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('last_done', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interval_months >= 1 AND interval_months <= 60', name='ck_maint_interval'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_schedules_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_schedules_next_due'), ['next_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_schedules_organization_id'), ['organization_id'], unique=False)

    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('ticket_type', sa.String(length=15), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('accessories_received', sa.Text(), nullable=True),
    sa.Column('reported_problem', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('scheduled_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('estimate_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('labour_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_approval', sa.String(length=15), nullable=False),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=False),
    sa.Column('maintenance_schedule_id', sa.Integer(), nullable=True),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('labour_charge >= 0', name='ck_ticket_labour'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['maintenance_schedule_id'], ['maintenance_schedules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number')
    )
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_tickets_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_tickets_org_status', ['organization_id', 'status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index('ix_tasks_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)

    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_events_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('returned_movement_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_ticket_part_qty'),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['returned_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_parts_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_part_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_invoice_lines_ticket_part_id', 'ticket_parts', ['ticket_part_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_sales_invoice_lines_ticket_part_id', type_='foreignkey')
        batch_op.drop_column('ticket_part_id')

    with op.batch_alter_table('ticket_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_parts_ticket_id'))

    op.drop_table('ticket_parts')
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_events_ticket_id'))

    op.drop_table('ticket_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_index('ix_tasks_org_status')
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))

    op.drop_table('tasks')
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_tickets_org_status')
        batch_op.drop_index(batch_op.f('ix_service_tickets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_assigned_to'))

    op.drop_table('service_tickets')
    with op.batch_alter_table('maintenance_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_schedules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_schedules_next_due'))
        batch_op.drop_index(batch_op.f('ix_maintenance_schedules_customer_id'))

    op.drop_table('maintenance_schedules')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_warranty_until'))
        batch_op.drop_index(batch_op.f('ix_assets_organization_id'))
        batch_op.drop_index('ix_assets_org_customer')

    op.drop_table('assets')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_work_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_organization_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_organization_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
