"""phase5 documents

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 18:03:45.669375
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('original_name', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(entity_type = 'general') = (entity_id IS NULL)", name='ck_docs_entity'),
    sa.CheckConstraint('size_bytes > 0', name='ck_docs_size_pos'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('stored_documents', schema=None) as batch_op:
        batch_op.create_index('ix_docs_org_entity', ['organization_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_docs_org_sha', ['organization_id', 'sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_documents_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_documents_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stored_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stored_documents_expires_on'))
        batch_op.drop_index('ix_docs_org_sha')
        batch_op.drop_index('ix_docs_org_entity')

    op.drop_table('stored_documents')
    # ### end Alembic commands ###
