"""phase6 monitoring

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03 18:17:34.762397
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_note', sa.String(length=200), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('monitor_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_agents_organization_id'), ['organization_id'], unique=False)

    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('latency_warn_ms', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('failing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('status_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'tcp') = (port IS NOT NULL)", name='ck_check_port'),
    sa.CheckConstraint('interval_seconds >= 30', name='ck_check_interval'),
    sa.ForeignKeyConstraint(['agent_id'], ['monitor_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_checks', schema=None) as batch_op:
        batch_op.create_index('ix_checks_org_agent', ['organization_id', 'agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_checks_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_checks_organization_id'), ['organization_id'], unique=False)

    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_id', 'observed_at')
    )
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_results_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_results_check_time', ['check_id', 'observed_at'], unique=False)

    op.create_table('monitor_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_check', ['check_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_incidents_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('firmware', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('recorder_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hdd_capacity_gb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retention_days', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_recorder_id'), ['recorder_id'], unique=False)
        batch_op.create_unique_constraint('uq_assets_recorder_channel', ['recorder_id', 'channel'])
        batch_op.create_foreign_key('fk_assets_recorder_id', 'assets', ['recorder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_assets_recorder_id', type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_assets_recorder_channel', type_='unique')
        batch_op.drop_index(batch_op.f('ix_assets_recorder_id'))
        batch_op.drop_column('retention_days')
        batch_op.drop_column('hdd_capacity_gb')
        batch_op.drop_column('resolution')
        batch_op.drop_column('channel')
        batch_op.drop_column('recorder_id')
        batch_op.drop_column('firmware')
        batch_op.drop_column('mac_address')

    with op.batch_alter_table('monitor_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_incidents_organization_id'))
        batch_op.drop_index('ix_incidents_check')

    op.drop_table('monitor_incidents')
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_check_time')
        batch_op.drop_index(batch_op.f('ix_check_results_organization_id'))

    op.drop_table('check_results')
    with op.batch_alter_table('monitor_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_checks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_checks_asset_id'))
        batch_op.drop_index('ix_checks_org_agent')

    op.drop_table('monitor_checks')
    with op.batch_alter_table('monitor_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_agents_organization_id'))

    op.drop_table('monitor_agents')
    # ### end Alembic commands ###
