"""phase7 endpoint security

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-03 18:35:36.311570
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=40), nullable=True),
    sa.Column('last_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defender_available', sa.Boolean(), nullable=False),
    sa.Column('av_enabled', sa.Boolean(), nullable=True),
    sa.Column('realtime_enabled', sa.Boolean(), nullable=True),
    sa.Column('antispyware_enabled', sa.Boolean(), nullable=True),
    sa.Column('behavior_monitor_enabled', sa.Boolean(), nullable=True),
    sa.Column('tamper_protected', sa.Boolean(), nullable=True),
    sa.Column('running_mode', sa.String(length=30), nullable=True),
    sa.Column('signature_version', sa.String(length=40), nullable=True),
    sa.Column('signature_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(length=40), nullable=True),
    sa.Column('product_version', sa.String(length=40), nullable=True),
    sa.Column('quick_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['monitor_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'hostname')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoints_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('endpoint_threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(length=64), nullable=False),
    sa.Column('threat_name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action_success', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledge_note', sa.Text(), nullable=True),
    sa.Column('times_reported', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'detection_id')
    )
    with op.batch_alter_table('endpoint_threats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoint_threats_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_threats_org_detected', ['organization_id', 'detected_at'], unique=False)

    with op.batch_alter_table('monitor_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collect_endpoint', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_agents', schema=None) as batch_op:
        batch_op.drop_column('collect_endpoint')

    with op.batch_alter_table('endpoint_threats', schema=None) as batch_op:
        batch_op.drop_index('ix_threats_org_detected')
        batch_op.drop_index(batch_op.f('ix_endpoint_threats_organization_id'))

    op.drop_table('endpoint_threats')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoints_organization_id'))
        batch_op.drop_index(batch_op.f('ix_endpoints_asset_id'))

    op.drop_table('endpoints')
    # ### end Alembic commands ###
