"""snmp checks

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-04 10:27:19.297072
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('values', sa.JSON(), nullable=True))

    with op.batch_alter_table('monitor_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snmp_community', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('snmp_oids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_values', sa.JSON(), nullable=True))
        # SNMP checks have a port (161), so the rule is now "only ICMP has no port".
        batch_op.drop_constraint('ck_check_port', type_='check')
        batch_op.create_check_constraint('ck_check_port', "(kind = 'icmp') = (port IS NULL)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM monitor_checks WHERE kind = 'snmp'")  # cannot exist in the old schema
    with op.batch_alter_table('monitor_checks', schema=None) as batch_op:
        batch_op.drop_constraint('ck_check_port', type_='check')
        batch_op.create_check_constraint('ck_check_port', "(kind = 'tcp') = (port IS NOT NULL)")
        batch_op.drop_column('last_values')
        batch_op.drop_column('snmp_oids')
        batch_op.drop_column('snmp_community')

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_column('values')

    # ### end Alembic commands ###
