"""text message alerts

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-04 10:31:04.180916
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=10), server_default='email', nullable=False))

    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM email_outbox WHERE channel <> 'email'")  # texts would look like emails to phone numbers
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.drop_column('sms')

    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
